<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Penghou.Baize" Version="0.3.0-preview.5" />
    <PackageReference Include="Penghou.Zhinu" Version="0.1.0-preview.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Guyabano.Artifacts\Guyabano.Artifacts.csproj" />
    <ProjectReference Include="..\Guyabano.CodeGeneration.Planning\Guyabano.CodeGeneration.Planning.csproj" />
    <ProjectReference Include="..\Guyabano.Session\Guyabano.Session.csproj" />
  </ItemGroup>

</Project>
