<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Penghou.Baize.Router" Version="0.3.0-preview.5" />
    <PackageReference Include="Penghou.Baize.Tools" Version="0.3.0-preview.5" />
    <PackageReference Include="Penghou.Fuwen" Version="0.1.0-preview.10" />
    <PackageReference Include="Penghou.Fuwen.Compiler" Version="0.1.0-preview.10" />
    <PackageReference Include="Penghou.Fuwen.Zhinu" Version="0.1.0-preview.10" />
    <PackageReference Include="Penghou.Guihua" Version="0.1.0-preview.1" />
    <PackageReference Include="Penghou.Guihua.Baize" Version="0.1.0-preview.1" />
    <PackageReference Include="Penghou.Zhinu" Version="0.1.0-preview.14" />
    <PackageReference Include="Penghou.Zhinu.Sqlite" Version="0.1.0-preview.14" />
    <ProjectReference Include="..\Guyabano.Artifacts\Guyabano.Artifacts.csproj" />
    <ProjectReference Include="..\Guyabano.Llm.Prompting\Guyabano.Llm.Prompting.csproj" />
  </ItemGroup>

</Project>



