<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="1.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0-pre.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="FluentAssertions" Version="7.*" />
    <PackageReference Include="Penghou.Cangjie.Sqlite" Version="0.1.0-preview.3" />
    <PackageReference Include="Penghou.Hetu.CSharp" Version="0.2.0-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\src\Guyabano.WorkflowWorker\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>worker-appsettings.json</TargetPath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Guyabano.WebTerminal\Guyabano.WebTerminal.csproj" />
    <ProjectReference Include="..\..\src\Guyabano.WorkflowWorker\Guyabano.WorkflowWorker.csproj" />
    <ProjectReference Include="..\..\src\Guyabano.Session.Sqlite\Guyabano.Session.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
